"""cases sets membership app_setting

Revision ID: 06574746d714
Revises:
Create Date: 2026-08-01 08:30:43.425870+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "06574746d714"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_setting",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("app_setting", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_app_setting_key"), ["key"], unique=True)

    op.create_table(
        "eval_case",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scoring_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tags_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eval_case", schema=None) as batch_op:
        batch_op.create_index("ix_eval_case_deleted_at", ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_case_title"), ["title"], unique=False)

    op.create_table(
        "eval_set",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tags_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("default_scoring_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eval_set", schema=None) as batch_op:
        batch_op.create_index("ix_eval_set_deleted_at", ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_set_name"), ["name"], unique=True)

    op.create_table(
        "set_membership",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["eval_case.id"],
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["eval_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("set_membership", schema=None) as batch_op:
        batch_op.create_index("ix_set_membership_case", ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_set_membership_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_set_membership_set_id"), ["set_id"], unique=False)
        batch_op.create_index(
            "ix_set_membership_set_position", ["set_id", "position"], unique=False
        )
        batch_op.create_index("uq_set_membership", ["set_id", "case_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("set_membership", schema=None) as batch_op:
        batch_op.drop_index("uq_set_membership")
        batch_op.drop_index("ix_set_membership_set_position")
        batch_op.drop_index(batch_op.f("ix_set_membership_set_id"))
        batch_op.drop_index(batch_op.f("ix_set_membership_case_id"))
        batch_op.drop_index("ix_set_membership_case")

    op.drop_table("set_membership")
    with op.batch_alter_table("eval_set", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_set_name"))
        batch_op.drop_index("ix_eval_set_deleted_at")

    op.drop_table("eval_set")
    with op.batch_alter_table("eval_case", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_case_title"))
        batch_op.drop_index("ix_eval_case_deleted_at")

    op.drop_table("eval_case")
    with op.batch_alter_table("app_setting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_app_setting_key"))

    op.drop_table("app_setting")
    # ### end Alembic commands ###
