"""executors runs items attempts

Revision ID: 71597924e800
Revises: 06574746d714
Create Date: 2026-08-01 08:57:18.413774+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "71597924e800"
down_revision: str | None = "06574746d714"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "harness_profile",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("harness_profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_harness_profile_archived"), ["archived"], unique=False)
        batch_op.create_index(batch_op.f("ix_harness_profile_name"), ["name"], unique=True)

    op.create_table(
        "model_profile",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("api_key_env", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("params_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pricing_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_profile_archived"), ["archived"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_profile_name"), ["name"], unique=True)

    op.create_table(
        "run",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_run_id", sa.Integer(), nullable=True),
        sa.Column("config_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("totals_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_baseline_for_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_parent_run_id"), ["parent_run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_status"), ["status"], unique=False)

    op.create_table(
        "executor",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_profile_id", sa.Integer(), nullable=False),
        sa.Column("harness_profile_id", sa.Integer(), nullable=False),
        sa.Column("overrides_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["harness_profile_id"],
            ["harness_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_profile_id"],
            ["model_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("executor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_executor_archived"), ["archived"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_executor_harness_profile_id"), ["harness_profile_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_executor_model_profile_id"), ["model_profile_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_executor_name"), ["name"], unique=True)

    op.create_table(
        "run_item",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=True),
        sa.Column("set_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("executor_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("case_snapshot_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("verdict", sa.Boolean(), nullable=True),
        sa.Column("score_value", sa.Float(), nullable=True),
        sa.Column("needs_human", sa.Boolean(), nullable=False),
        sa.Column("current_attempt_id", sa.Integer(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_item_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_run_item_executor_key"), ["executor_key"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_run_item_needs_human"), ["needs_human"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_item_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            "ix_run_item_run_lane", ["run_id", "executor_key", "position"], unique=False
        )
        batch_op.create_index("ix_run_item_run_status", ["run_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_item_set_id"), ["set_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_item_status"), ["status"], unique=False)

    op.create_table(
        "attempt",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_item_id", sa.Integer(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("request_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("output_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("messages_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column("purpose", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_item_id"],
            ["run_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attempt", schema=None) as batch_op:
        batch_op.create_index("ix_attempt_item_n", ["run_item_id", "n"], unique=False)
        batch_op.create_index(batch_op.f("ix_attempt_run_item_id"), ["run_item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_attempt_superseded"), ["superseded"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attempt_superseded"))
        batch_op.drop_index(batch_op.f("ix_attempt_run_item_id"))
        batch_op.drop_index("ix_attempt_item_n")

    op.drop_table("attempt")
    with op.batch_alter_table("run_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_item_status"))
        batch_op.drop_index(batch_op.f("ix_run_item_set_id"))
        batch_op.drop_index("ix_run_item_run_status")
        batch_op.drop_index("ix_run_item_run_lane")
        batch_op.drop_index(batch_op.f("ix_run_item_run_id"))
        batch_op.drop_index(batch_op.f("ix_run_item_needs_human"))
        batch_op.drop_index(batch_op.f("ix_run_item_executor_key"))
        batch_op.drop_index(batch_op.f("ix_run_item_case_id"))

    op.drop_table("run_item")
    with op.batch_alter_table("executor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_executor_name"))
        batch_op.drop_index(batch_op.f("ix_executor_model_profile_id"))
        batch_op.drop_index(batch_op.f("ix_executor_harness_profile_id"))
        batch_op.drop_index(batch_op.f("ix_executor_archived"))

    op.drop_table("executor")
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_status"))
        batch_op.drop_index(batch_op.f("ix_run_parent_run_id"))

    op.drop_table("run")
    with op.batch_alter_table("model_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_profile_name"))
        batch_op.drop_index(batch_op.f("ix_model_profile_archived"))

    op.drop_table("model_profile")
    with op.batch_alter_table("harness_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_harness_profile_name"))
        batch_op.drop_index(batch_op.f("ix_harness_profile_archived"))

    op.drop_table("harness_profile")
    # ### end Alembic commands ###
