"""artifact table

Revision ID: a211244b9eea
Revises: a8d4ed638ed0
Create Date: 2026-08-01 17:17:45.414556+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "a211244b9eea"
down_revision: str | None = "a8d4ed638ed0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mime", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rel_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("block_index", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifact", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifact_attempt_id"), ["attempt_id"], unique=False)
        batch_op.create_index("ix_artifact_attempt_kind", ["attempt_id", "kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifact_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifact_sha256"), ["sha256"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifact_sha256"))
        batch_op.drop_index(batch_op.f("ix_artifact_kind"))
        batch_op.drop_index("ix_artifact_attempt_kind")
        batch_op.drop_index(batch_op.f("ix_artifact_attempt_id"))

    op.drop_table("artifact")
    # ### end Alembic commands ###
