"""score table

Revision ID: a8d4ed638ed0
Revises: 71597924e800
Create Date: 2026-08-01 09:34:57.788062+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "a8d4ed638ed0"
down_revision: str | None = "71597924e800"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "score",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_item_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=True),
        sa.Column("scorer_index", sa.Integer(), nullable=False),
        sa.Column("scorer_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scorer_config_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("rationale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("judge_meta_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_item_id"],
            ["run_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_score_attempt_id"), ["attempt_id"], unique=False)
        batch_op.create_index(
            "ix_score_item_scorer", ["run_item_id", "scorer_index", "version"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_score_run_item_id"), ["run_item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_score_source"), ["source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_score_source"))
        batch_op.drop_index(batch_op.f("ix_score_run_item_id"))
        batch_op.drop_index("ix_score_item_scorer")
        batch_op.drop_index(batch_op.f("ix_score_attempt_id"))

    op.drop_table("score")
    # ### end Alembic commands ###
